
[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.7.0"

[[constraint]]
  name = "github.com/izumin5210/grapi"
  version = "0.3.2"
