// Code generated by github.com/izumin5210/grapi. DO NOT EDIT.

package server

import (
	api_pb "google.golang.org/genproto/googleapis/pubsub/v1"
	"google.golang.org/grpc"
)

// RegisterWithServer implements grapiserver.Server.RegisterWithServer.
func (s *publisherServiceServerImpl) RegisterWithServer(grpcSvr *grpc.Server) {
	api_pb.RegisterPublisherServer(grpcSvr, s)
}
