// Code generated by github.com/izumin5210/grapi. DO NOT EDIT.

package server

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	api_pb "github.com/rerost/chaos-pubsub/api"
	"google.golang.org/grpc"
)

// RegisterWithServer implements grapiserver.Server.RegisterWithServer.
func (s *subscriberServiceServerImpl) RegisterWithServer(grpcSvr *grpc.Server) {
	api_pb.RegisterSubscriberServer(grpcSvr, s)
}

// RegisterWithHandler implements grapiserver.Server.RegisterWithHandler.
func (s *subscriberServiceServerImpl) RegisterWithHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return api_pb.RegisterSubscriberHandler(ctx, mux, conn)
}
